name: BSMath Test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]

jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: lukka/get-cmake@latest
      - name: Generate project files
        run: ${{ github.workspace }}/Scripts/Setup
      - name: Build
        run: ${{ github.workspace }}/Scripts/Build
      - name: Test
        working-directory: ./Binaries
        run: ./BSMath-Tests

  job:
    name: ${{ matrix.os }}-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: lukka/get-cmake@latest
      - name: Generate project files
        run: sh ${{ github.workspace }}/Scripts/Setup.sh
      - name: Build
        run: sh ${{ github.workspace }}/Scripts/Build.sh
      - name: Test
        working-directory: ./Binaries
        run: ./BSMath-Tests