name: BSMath Test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snickerbockers/submodules-init@v4
    - name: Get GTest
      run: sh ./Scripts/GetGTest.sh
    - name: Create Build Environment
      run: cmake -E make_directory Binaries/Tests
    - name: Build
      working-directory: ./Binaries/Tests
      run: cmake ../.. && cmake --build . --config $Build_TYPE
    - name: Run Test
      working-directory: ./Binaries/Tests/Tests
      run: ./BSMath-Tests
